stages:
  - base
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  CI_REGISTRY_USER: faxrij
  APP_NAME: spring-boot-gitlab
  REPO: TODO_APP_BACKEND
  CI_IMAGE_TAG: ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
  CI_BASE_IMAGE: ${CI_REGISTRY_IMAGE}/base:latest
  CI_REGISTRY: registry.gitlab.com/faxrij/$REPO

cache:
  paths:
    - .m2/repository/

#build:
#  image: docker:18.09
#  stage: build
#  services:
#    - docker:18.09-dind
#  variables:
#    DOCKER_HOST: tcp://docker:2376
#    DOCKER_TLS_CERTDIR: '/certs'
#    DOCKER_DRIVER: overlay2
#    before_script:
#      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#
#  script:
#    - docker build
#      --network host
#      --tag $CI_REGISTRY_IMAGE:$CI_IMAGE_TAG
#      .
#    - docker tag $CI_REGISTRY_IMAGE:$CI_IMAGE_TAG $CI_REGISTRY_IMAGE:latest
#    - docker push $CI_REGISTRY_IMAGE:$CI_IMAGE_TAG

test:
  stage: test
  image: $CI_REGISTRY
  services:
    - docker:18.09-dind
  variables:
    SPRING_PROFILES_ACTIVE: local
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
    DOCKER_DRIVER: overlay2
  script:
    - mvn verify
  artifacts:
    when: on_failure
    paths:
      - target/surefire-reports

#<<<<<<< HEAD
deploy:
  stage: deploy
  artifacts:
    expire_in: 1 month
  script:
    - mvn clean package -B
    - ls target/classes/

#=======
#deploy:
#  stage: deploy
#  artifacts:
#    expire_in: 1 month
#  script:
#    - mvn clean package -B
#    - ls target/classes/
#>>>>>>> 5b16456 (commit)
